# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      datacentre: 'global1'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']


  - job_name: consul
    consul_sd_configs:
      - server: 'consul:8500'
        services: []
    relabel_configs:
        - source_labels: ['__meta_consul_service']
          regex:         '(.*)'
          target_label:  'job'
          replacement:   '$1'
        - source_labels: ['__meta_consul_service_address']
          regex:         '(.*)'
          target_label:  'instance'
          replacement:   '$1'
        - source_labels: ['__meta_consul_service_address', '__meta_consul_service_port']
          regex:         '(.*);(.*)'
          target_label:  '__address__'
          replacement:   '$1:$2'
        - source_labels: ['__meta_consul_tags']
          regex:         ',(metrics),'
          action:        keep



  - job_name: downstream_prometheus
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
        - '{__name__=~"^job:.*"}'
        - '{job="prometheus"}'
    static_configs:
      - targets:
        - eu-west-1-prometheus:9090
        - eu-west-2-prometheus:9090


#These are scraped via consul and registrator

  # - job_name: nginx
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets:
  #     - nginx-exporter:9913
  #     - nginx-exporter2:9913

  # - job_name: nginx-lula
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets:
  #     - nginx-lula:9145

  # - job_name: mesos
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets:
  #     - mesos-exporter:9105


alerting:
 alert_relabel_configs:
 - source_labels: []
   regex: (.+)\d+
   target_label: nginx
 alertmanagers:
 - static_configs:
   - targets: ['alertmanager1:9093', 'alertmanager2:9093']

